-- Untuk tabel accounts
ALTER TABLE accounts
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

-- Untuk tabel categories
ALTER TABLE categories
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

-- Untuk tabel transactions
ALTER TABLE transactions
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
